# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Apple Installer Checksums
description: >
  Cryptographic checksums for Apple installers.
baseurl: "/apple-installer-checksums"
url: "https://notpeter.github.io"
twitter_username: notpeter
github_username:  notpeter/apple-installer-checksums
github_project: apple-installer-checksums

# Build settings
theme: minima
plugins:
  - jekyll-feed           #figure out how to remove this.
  - jekyll-relative-links
  - jekyll-toc
exclude:
  - Gemfile
  - Gemfile.lock
  - readme.md
# This is not a jekyll thing, it's just a hard coded array
anchors:
  - {url: '/', title: 'Mac OS X'}
  - {url: '#mac-osx-installers-sha1-checksums', title: 'Verify'}
  - {url: '/xcode', title: 'XCode'}
  - {url: '#about', title: 'About'}
  - {url: '#contribute', title: 'Contribute'}