source "https://rubygems.org"
ruby RUBY_VERSION
gem "jekyll"
#gem "github-pages", group: :jekyll_plugins

# Originally tested with minima 2.1.0
gem "minima"

group :jekyll_plugins do
    gem "jekyll-feed"
    gem 'jekyll-relative-links'
end
gem 'github-pages', group: :jekyll_plugins

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
