source "https://rubygems.org"
ruby RUBY_VERSION
# bundle install; bundle exec jekyll serve
gem "jekyll", "3.4.3"
#gem "github-pages", group: :jekyll_plugins

# Originally tested with minima 2.1.0
gem "minima", "~> 2.0"

group :jekyll_plugins do
   gem "jekyll-feed", "~> 0.6"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
